import React, { useState, useEffect } from 'react'
import { Layout } from '../Layout'
import { Button } from '../ui/button'
import { Card } from '../ui/card'
import { Badge } from '../ui/badge'
import { Progress } from '../ui/progress'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs'
import { Separator } from '../ui/separator'
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar, Area, AreaChart } from 'recharts'

export function CashflowResultatenPage() {
  const [scanData, setScanData] = useState<any>(null)
  const [customerInfo, setCustomerInfo] = useState<any>(null)
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    // Simulate loading and get data from localStorage
    const timer = setTimeout(() => {
      const storedData = localStorage.getItem('simium_scan_data')
      if (storedData) {
        const parsed = JSON.parse(storedData)
        if (parsed.scanType === 'cashflow') {
          setScanData(parsed.data)
        }
      }
      
      // Get customer info from localStorage or use mock data
      const customerData = localStorage.getItem('simium_customer_info')
      if (customerData) {
        setCustomerInfo(JSON.parse(customerData))
      } else {
        // Mock customer data for demo
        setCustomerInfo({
          name: 'Maria Jansen',
          company: 'Innovate Marketing B.V.',
          email: 'maria@innovatemarketing.nl',
          analysisDate: new Date().toLocaleDateString('nl-NL', { 
            day: 'numeric', 
            month: 'long', 
            year: 'numeric' 
          })
        })
      }
      
      setIsLoading(false)
    }, 1500)

    return () => clearTimeout(timer)
  }, [])

  const handleDownloadPDF = () => {
    const element = document.createElement('a')
    const file = new Blob(['Cashflow Analyse Rapport - Generated by Simium AI'], { type: 'text/plain' })
    element.href = URL.createObjectURL(file)
    element.download = 'simium-cashflow-analyse.pdf'
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  // Mock data based on scan inputs
  const mockAnalysisData = {
    monthlyRevenue: parseInt(scanData?.monthlyRevenue || '25000'),
    cashflowScore: scanData?.calculatedScore || 75,
    riskLevel: 'Gemiddeld',
    bufferOptimization: 3200,
    forecastAccuracy: 85
  }

  const cashflowForecast = [
    { month: 'Jul', inflow: 28000, outflow: 22000, net: 6000, optimized: 8500 },
    { month: 'Aug', inflow: 26000, outflow: 23500, net: 2500, optimized: 5200 },
    { month: 'Sep', inflow: 31000, outflow: 24000, net: 7000, optimized: 9200 },
    { month: 'Okt', inflow: 35000, outflow: 26000, net: 9000, optimized: 11500 },
    { month: 'Nov', inflow: 42000, outflow: 28000, net: 14000, optimized: 16200 },
    { month: 'Dec', inflow: 38000, outflow: 30000, net: 8000, optimized: 10800 }
  ]

  const paymentAnalysis = [
    { term: 'Direct', percentage: 25, days: 0, risk: 'Laag' },
    { term: '30 dagen', percentage: 45, days: 35, risk: 'Laag' },
    { term: '60 dagen', percentage: 25, days: 68, risk: 'Gemiddeld' },
    { term: '90+ dagen', percentage: 5, days: 95, risk: 'Hoog' }
  ]

  const seasonalPatterns = [
    { period: 'Q1', revenue: 22000, variance: 15 },
    { period: 'Q2', revenue: 28000, variance: 8 },
    { period: 'Q3', revenue: 25000, variance: 12 },
    { period: 'Q4', revenue: 35000, variance: 20 }
  ]

  const expenseCategories = [
    { category: 'Salarissen', amount: 12000, predictability: 95 },
    { category: 'Huur/Utilities', amount: 3500, predictability: 98 },
    { category: 'Marketing', amount: 4200, predictability: 60 },
    { category: 'Inkoop', amount: 6800, predictability: 45 },
    { category: 'Overig', amount: 2100, predictability: 30 }
  ]

  if (isLoading) {
    return (
      <Layout>
        <div className="min-h-screen flex items-center justify-center bg-gray-50">
          <Card className="p-8 max-w-md w-full text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
            <h3 className="mb-2">AI analyseert je cashflow...</h3>
            <p className="text-gray-600 text-sm">
              Onze AI voorspelt je kasstromen en identificeert optimalisaties
            </p>
            <Progress value={75} className="mt-4" />
            <p className="text-xs text-gray-500 mt-2">Patronen herkennen...</p>
          </Card>
        </div>
      </Layout>
    )
  }

  return (
    <Layout>
      {/* Header */}
      <div className="bg-gradient-to-r from-blue-600 to-blue-700 text-white mx-4 rounded-2xl mb-8">
        <div className="max-w-6xl mx-auto px-4 sm:px-8 py-8">

          
          <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Badge className="bg-white/20 text-white">Cashflow-analyse</Badge>
                <Badge className="bg-white/20 text-white">Voltooid</Badge>
              </div>
              <h1 className="text-2xl lg:text-3xl text-white mb-2">
                Je cashflow-analyse is klaar
              </h1>
              <p className="text-blue-100">
                Gegenereerd op {customerInfo?.analysisDate || new Date().toLocaleDateString('nl-NL', { 
                  day: 'numeric', 
                  month: 'long', 
                  year: 'numeric' 
                })}
              </p>
            </div>
            <div className="flex justify-end">
              <Button 
                onClick={handleDownloadPDF}
                className="bg-white text-blue-600 hover:bg-blue-50 text-[14px]"
              >
                Download PDF
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Customer Info Banner */}
      {customerInfo && (
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 mb-8">
          <div className="bg-white rounded-xl p-4 border border-gray-200 shadow-sm">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center">
                  <span className="text-blue-600 text-lg">{customerInfo.name?.charAt(0) || 'M'}</span>
                </div>
                <div>
                  <div className="text-gray-900 font-medium">{customerInfo.name}</div>
                  <div className="text-gray-600 text-sm">{customerInfo.company}</div>
                </div>
              </div>
              <div className="text-right">
                <div className="text-gray-600 text-sm">Persoonlijke analyse voor</div>
                <div className="text-gray-900 text-sm font-medium">{customerInfo.email}</div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Key Metrics */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 mb-8">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <Card className="p-6 bg-gradient-to-br from-blue-50 to-blue-100">
            <div className="text-center">
              <div className="text-3xl text-blue-600 mb-2">{mockAnalysisData.cashflowScore}/100</div>
              <div className="text-gray-700 mb-1">Cashflow score</div>
              <div className="text-blue-600 text-sm">Goed met verbeterpotentieel</div>
            </div>
          </Card>
          
          <Card className="p-6">
            <div className="text-center">
              <div className="text-3xl text-green-600 mb-2">
                €{mockAnalysisData.bufferOptimization.toLocaleString()}
              </div>
              <div className="text-gray-700 mb-1">Buffer optimalisatie</div>
              <div className="text-green-600 text-sm">Minder cash buffer nodig</div>
            </div>
          </Card>
          
          <Card className="p-6">
            <div className="text-center">
              <div className="text-3xl text-purple-600 mb-2">{mockAnalysisData.forecastAccuracy}%</div>
              <div className="text-gray-700 mb-1">Voorspelling accuratesse</div>
              <div className="text-purple-600 text-sm">Hoge betrouwbaarheid</div>
            </div>
          </Card>
          
          <Card className="p-6">
            <div className="text-center">
              <div className="text-3xl text-orange-600 mb-2">{mockAnalysisData.riskLevel}</div>
              <div className="text-gray-700 mb-1">Risico niveau</div>
              <div className="text-orange-600 text-sm">Beheersbaar met planning</div>
            </div>
          </Card>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 mb-8">
        <Tabs defaultValue="forecast" className="w-full">
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="forecast">Voorspelling</TabsTrigger>
            <TabsTrigger value="patterns">Patronen</TabsTrigger>
            <TabsTrigger value="risks">Risico's</TabsTrigger>
            <TabsTrigger value="optimization">Optimalisatie</TabsTrigger>
          </TabsList>

          <TabsContent value="forecast" className="space-y-6">
            <Card className="p-6">
              <h3 className="mb-4">6-maanden cashflow voorspelling</h3>
              <ResponsiveContainer width="100%" height={400}>
                <AreaChart data={cashflowForecast}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="month" />
                  <YAxis />
                  <Tooltip formatter={(value) => [`€${value?.toLocaleString()}`, '']} />
                  <Area type="monotone" dataKey="inflow" stackId="1" stroke="#16a34a" fill="#16a34a" fillOpacity={0.3} name="Inkomsten" />
                  <Area type="monotone" dataKey="outflow" stackId="2" stroke="#ef4444" fill="#ef4444" fillOpacity={0.3} name="Uitgaven" />
                  <Line type="monotone" dataKey="net" stroke="#2563eb" strokeWidth={3} name="Netto cashflow" />
                  <Line type="monotone" dataKey="optimized" stroke="#7c3aed" strokeWidth={2} strokeDasharray="5 5" name="Geoptimaliseerd" />
                </AreaChart>
              </ResponsiveContainer>
            </Card>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <Card className="p-6">
                <h4 className="mb-4">Cashflow per maand</h4>
                <div className="space-y-4">
                  {cashflowForecast.map((month) => (
                    <div key={month.month} className="flex justify-between items-center">
                      <div>
                        <div className="font-medium">{month.month}</div>
                        <div className="text-sm text-gray-600">
                          In: €{month.inflow.toLocaleString()} | Uit: €{month.outflow.toLocaleString()}
                        </div>
                      </div>
                      <div className="text-right">
                        <div className={`font-medium ${month.net > 0 ? 'text-green-600' : 'text-red-600'}`}>
                          €{month.net.toLocaleString()}
                        </div>
                        <div className="text-sm text-purple-600">
                          Opt: €{month.optimized.toLocaleString()}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </Card>

              <Card className="p-6">
                <h4 className="mb-4">Liquiditeitsbuffer aanbeveling</h4>
                <div className="space-y-4">
                  <div className="text-center p-4 bg-blue-50 rounded-lg">
                    <div className="text-2xl text-blue-600 mb-2">€18.500</div>
                    <div className="text-sm text-gray-600">Aanbevolen buffer</div>
                  </div>
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <span className="text-sm text-gray-600">Huidige buffer</span>
                      <span className="text-sm">€22.000</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-sm text-gray-600">Minimaal vereist</span>
                      <span className="text-sm">€15.000</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-sm text-gray-600">Optimaal niveau</span>
                      <span className="text-sm text-blue-600">€18.500</span>
                    </div>
                    <div className="flex justify-between font-medium border-t pt-2">
                      <span className="text-sm">Vrij te maken</span>
                      <span className="text-sm text-green-600">€3.500</span>
                    </div>
                  </div>
                </div>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="patterns" className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <Card className="p-6">
                <h4 className="mb-4">Seizoenspatronen</h4>
                <ResponsiveContainer width="100%" height={300}>
                  <BarChart data={seasonalPatterns}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="period" />
                    <YAxis />
                    <Tooltip formatter={(value) => [`€${value?.toLocaleString()}`, 'Gemiddelde omzet']} />
                    <Bar dataKey="revenue" fill="#2563eb" />
                  </BarChart>
                </ResponsiveContainer>
              </Card>

              <Card className="p-6">
                <h4 className="mb-4">Betaaltermijn analyse</h4>
                <div className="space-y-4">
                  {paymentAnalysis.map((term) => (
                    <div key={term.term} className="flex justify-between items-center">
                      <div>
                        <div className="font-medium">{term.term}</div>
                        <div className="text-sm text-gray-600">{term.percentage}% van omzet</div>
                      </div>
                      <div className="text-right">
                        <div className="text-sm">Gem. {term.days} dagen</div>
                        <Badge 
                          variant="outline" 
                          className={
                            term.risk === 'Laag' ? 'text-green-600 border-green-600' :
                            term.risk === 'Gemiddeld' ? 'text-orange-600 border-orange-600' :
                            'text-red-600 border-red-600'
                          }
                        >
                          {term.risk}
                        </Badge>
                      </div>
                    </div>
                  ))}
                </div>
              </Card>
            </div>

            <Card className="p-6">
              <h4 className="mb-4">Uitgavenpatroon voorspelbaarheid</h4>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {expenseCategories.map((expense) => (
                  <Card key={expense.category} className="p-4">
                    <div className="flex justify-between items-start mb-3">
                      <div>
                        <div className="font-medium">{expense.category}</div>
                        <div className="text-sm text-gray-600">€{expense.amount.toLocaleString()}/maand</div>
                      </div>
                      <Badge 
                        variant="outline"
                        className={
                          expense.predictability >= 90 ? 'text-green-600 border-green-600' :
                          expense.predictability >= 70 ? 'text-blue-600 border-blue-600' :
                          expense.predictability >= 50 ? 'text-orange-600 border-orange-600' :
                          'text-red-600 border-red-600'
                        }
                      >
                        {expense.predictability}%
                      </Badge>
                    </div>
                    <Progress value={expense.predictability} className="h-2" />
                    <div className="text-xs text-gray-500 mt-1">Voorspelbaarheid</div>
                  </Card>
                ))}
              </div>
            </Card>
          </TabsContent>

          <TabsContent value="risks" className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <Card className="p-6 border-red-200 bg-red-50">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 bg-red-100 rounded-full flex items-center justify-center">
                    <span className="w-2 h-2 bg-red-600 rounded-full"></span>
                  </div>
                  <div>
                    <h4 className="text-red-800">Hoge risico's</h4>
                    <p className="text-sm text-red-600">Direct aandacht vereist</p>
                  </div>
                </div>
                <ul className="space-y-3">
                  <li className="flex items-start gap-3">
                    <span className="text-red-500 mt-1">•</span>
                    <div>
                      <div className="font-medium text-red-800">Lange betaaltermijnen</div>
                      <div className="text-sm text-red-600">30% van klanten betaalt &gt;60 dagen</div>
                      <div className="text-sm text-red-600">Impact: €8.500 vertraagde cashflow</div>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-red-500 mt-1">•</span>
                    <div>
                      <div className="font-medium text-red-800">Seizoensfluctuaties Q4</div>
                      <div className="text-sm text-red-600">40% meer omzet, maar ook 25% meer kosten</div>
                      <div className="text-sm text-red-600">Risico: Overcapaciteit in Q1</div>
                    </div>
                  </li>
                </ul>
              </Card>

              <Card className="p-6 border-orange-200 bg-orange-50">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 bg-orange-100 rounded-full flex items-center justify-center">
                    <span className="w-2 h-2 bg-orange-600 rounded-full"></span>
                  </div>
                  <div>
                    <h4 className="text-orange-800">Gemiddelde risico's</h4>
                    <p className="text-sm text-orange-600">Monitoring aanbevolen</p>
                  </div>
                </div>
                <ul className="space-y-3">
                  <li className="flex items-start gap-3">
                    <span className="text-orange-500 mt-1">•</span>
                    <div>
                      <div className="font-medium text-orange-800">Onvoorspelbare marketing uitgaven</div>
                      <div className="text-sm text-orange-600">60% voorspelbaarheid</div>
                      <div className="text-sm text-orange-600">Adviseer: Budgettering per kwartaal</div>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-orange-500 mt-1">•</span>
                    <div>
                      <div className="font-medium text-orange-800">Klantconcentratie</div>
                      <div className="text-sm text-orange-600">Top 3 klanten = 45% van omzet</div>
                      <div className="text-sm text-orange-600">Risico: Afhankelijkheid</div>
                    </div>
                  </li>
                </ul>
              </Card>
            </div>

            <Card className="p-6">
              <h4 className="mb-4">Scenario analyse</h4>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="text-center">
                  <div className="text-lg mb-2">Basis scenario</div>
                  <div className="text-2xl text-blue-600 mb-2">€45.000</div>
                  <div className="text-sm text-gray-600">Gem. maandelijkse cashflow</div>
                  <div className="text-xs text-gray-500 mt-2">85% waarschijnlijkheid</div>
                </div>
                <div className="text-center">
                  <div className="text-lg mb-2">Optimistisch</div>
                  <div className="text-2xl text-green-600 mb-2">€58.000</div>
                  <div className="text-sm text-gray-600">Bij snellere betalingen</div>
                  <div className="text-xs text-gray-500 mt-2">25% waarschijnlijkheid</div>
                </div>
                <div className="text-center">
                  <div className="text-lg mb-2">Pessimistisch</div>
                  <div className="text-2xl text-red-600 mb-2">€28.000</div>
                  <div className="text-sm text-gray-600">Bij betalingsvertragingen</div>
                  <div className="text-xs text-gray-500 mt-2">15% waarschijnlijkheid</div>
                </div>
              </div>
            </Card>
          </TabsContent>

          <TabsContent value="optimization" className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <Card className="p-6">
                <h4 className="mb-4">Direct implementeerbaar</h4>
                <ul className="space-y-4">
                  <li className="flex items-start gap-3">
                    <span className="w-2 h-2 bg-green-500 rounded-full mt-2 flex-shrink-0"></span>
                    <div>
                      <div className="font-medium">Kortere betaaltermijnen</div>
                      <div className="text-sm text-gray-600">Verhoog cashflow met €3.200/maand</div>
                      <div className="text-sm text-blue-600">2% vroegbetaalkorting invoeren</div>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="w-2 h-2 bg-green-500 rounded-full mt-2 flex-shrink-0"></span>
                    <div>
                      <div className="font-medium">Automatische betalingsherinneringen</div>
                      <div className="text-sm text-gray-600">Verminder betaalvertraging met 8 dagen</div>
                      <div className="text-sm text-blue-600">Impact: €2.100 eerder beschikbaar</div>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="w-2 h-2 bg-green-500 rounded-full mt-2 flex-shrink-0"></span>
                    <div>
                      <div className="font-medium">Maandelijkse factuurperiode</div>
                      <div className="text-sm text-gray-600">Voorspelbaarder dan quarterly billing</div>
                      <div className="text-sm text-blue-600">Verbeter cashflow stabiliteit</div>
                    </div>
                  </li>
                </ul>
              </Card>

              <Card className="p-6">
                <h4 className="mb-4">Strategische optimalisaties</h4>
                <ul className="space-y-4">
                  <li className="flex items-start gap-3">
                    <span className="text-blue-500 mt-1">→</span>
                    <div>
                      <div className="font-medium">Dynamische pricing seizoenen</div>
                      <div className="text-sm text-gray-600">Verhoog marges in Q4, verlager in Q1</div>
                      <div className="text-sm text-blue-600">Vla cashflow over het jaar</div>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-blue-500 mt-1">→</span>
                    <div>
                      <div className="font-medium">Creditmanagement systeem</div>
                      <div className="text-sm text-gray-600">Automatiseer debiteuren management</div>
                      <div className="text-sm text-blue-600">Verminder DSO met 12 dagen</div>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-blue-500 mt-1">→</span>
                    <div>
                      <div className="font-medium">Diversificatie klantbase</div>
                      <div className="text-sm text-gray-600">Verminder afhankelijkheid top klanten</div>
                      <div className="text-sm text-blue-600">Target: Geen klant &gt;15% van omzet</div>
                    </div>
                  </li>
                </ul>
              </Card>
            </div>

            <Card className="p-6">
              <h4 className="mb-4">Implementatie roadmap</h4>
              <div className="space-y-6">
                <div className="flex items-start gap-4">
                  <div className="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center flex-shrink-0">
                    <span className="text-green-600 text-sm">1</span>
                  </div>
                  <div className="flex-1">
                    <h5>Maand 1: Quick wins</h5>
                    <p className="text-sm text-gray-600 mb-2">Implementeer directe verbeteringen</p>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                      <div>• Vroegbetaalkorting invoeren</div>
                      <div>• Automatische herinneringen</div>
                      <div>• Betaaltermijnen aanpassen</div>
                      <div>• Factuurfrequentie verhogen</div>
                    </div>
                    <div className="mt-2 text-sm text-green-600">Impact: +€5.300 cashflow/maand</div>
                  </div>
                </div>

                <div className="flex items-start gap-4">
                  <div className="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center flex-shrink-0">
                    <span className="text-blue-600 text-sm">2</span>
                  </div>
                  <div className="flex-1">
                    <h5>Maand 2-3: Processen optimaliseren</h5>
                    <p className="text-sm text-gray-600 mb-2">Systematisch debiteuren management</p>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                      <div>• Creditcheck nieuwe klanten</div>
                      <div>• Geautomatiseerd incasso</div>
                      <div>• Dashboard cashflow monitoring</div>
                      <div>• KPI targets vaststellen</div>
                    </div>
                    <div className="mt-2 text-sm text-blue-600">Impact: +€2.800 extra stabiliteit</div>
                  </div>
                </div>

                <div className="flex items-start gap-4">
                  <div className="w-8 h-8 bg-purple-100 rounded-full flex items-center justify-center flex-shrink-0">
                    <span className="text-purple-600 text-sm">3</span>
                  </div>
                  <div className="flex-1">
                    <h5>Maand 4-6: Strategische optimalisaties</h5>
                    <p className="text-sm text-gray-600 mb-2">Langetermijn cashflow management</p>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                      <div>• Klantportfolio diversificatie</div>
                      <div>• Seizoensoptimalisatie pricing</div>
                      <div>• Predictive analytics</div>
                      <div>• Cashflow stress testing</div>
                    </div>
                    <div className="mt-2 text-sm text-purple-600">Impact: Structurele verbetering</div>
                  </div>
                </div>
              </div>
            </Card>
          </TabsContent>
        </Tabs>
      </div>

      {/* Bottom CTA */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 mb-8">
        <Card className="p-8 bg-gradient-to-r from-blue-50 to-blue-100 text-center">
          <h3 className="mb-4">Klaar om je cashflow te optimaliseren?</h3>
          <p className="text-gray-600 mb-6">
            Verhoog je cashflow met €8.100 per maand door onze aanbevelingen te implementeren.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              onClick={handleDownloadPDF}
              className="bg-blue-600 hover:bg-blue-700 text-white text-[14px]"
            >
              Download volledige analyse
            </Button>
            <a href="#/contact">
              <Button 
                variant="outline" 
                className="border-blue-600 text-blue-600 hover:bg-blue-50 text-[14px]"
              >
                Hulp bij implementatie?
              </Button>
            </a>
          </div>
        </Card>
      </div>
    </Layout>
  )
}