'use client'

import React, { useState, useEffect } from 'react'
import { Button } from '../ui/button'
import { Card } from '../ui/card'
import { Badge } from '../ui/badge'
import { Progress } from '../ui/progress'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs'
import { Separator } from '../ui/separator'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, LineChart, Line } from 'recharts'

export function CloudkostenResultatenPage() {
  const [scanData, setScanData] = useState<any>(null)
  const [customerInfo, setCustomerInfo] = useState<any>(null)
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    // Simulate loading and get data from localStorage
    const timer = setTimeout(() => {
      const storedData = localStorage.getItem('simium_scan_data')
      if (storedData) {
        const parsed = JSON.parse(storedData)
        if (parsed.scanType === 'cloudkosten') {
          setScanData(parsed.data)
        }
      }
      
      // Get customer info from localStorage or use mock data
      const customerData = localStorage.getItem('simium_customer_info')
      if (customerData) {
        setCustomerInfo(JSON.parse(customerData))
      } else {
        // Mock customer data for demo
        setCustomerInfo({
          name: 'Alex van den Berg',
          company: 'TechFlow Solutions B.V.',
          email: 'alex@techflow.nl',
          analysisDate: new Date().toLocaleDateString('nl-NL', { 
            day: 'numeric', 
            month: 'long', 
            year: 'numeric' 
          })
        })
      }
      
      setIsLoading(false)
    }, 1500)

    return () => clearTimeout(timer)
  }, [])

  const handleDownloadPDF = () => {
    // In a real app, this would generate and download a PDF
    const element = document.createElement('a')
    const file = new Blob(['Cloudkosten Analyse Rapport - Generated by Simium AI'], { type: 'text/plain' })
    element.href = URL.createObjectURL(file)
    element.download = 'simium-cloudkosten-analyse.pdf'
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  // Mock data based on scan inputs
  const mockAnalysisData = {
    totalMonthlyCost: parseInt(scanData?.monthlySpend || '5000'),
    projectedSavings: 2850,
    optimizationScore: 73,
    recommendations: 12,
    timeToImplement: '2-3 weken'
  }

  const costBreakdown = [
    { name: 'EC2 Instances', current: 3200, optimized: 1890, savings: 1310 },
    { name: 'RDS Databases', current: 1100, optimized: 780, savings: 320 },
    { name: 'Storage (EBS/S3)', current: 450, optimized: 280, savings: 170 },
    { name: 'Load Balancers', current: 180, optimized: 120, savings: 60 },
    { name: 'CloudWatch', current: 70, optimized: 50, savings: 20 }
  ]

  const utilizationData = [
    { name: 'Compute', utilized: 45, idle: 55 },
    { name: 'Storage', utilized: 62, idle: 38 },
    { name: 'Network', utilized: 78, idle: 22 },
    { name: 'Database', utilized: 34, idle: 66 }
  ]

  const monthlyTrend = [
    { month: 'Jan', cost: 4200 },
    { month: 'Feb', cost: 4650 },
    { month: 'Mar', cost: 5100 },
    { month: 'Apr', cost: 5400 },
    { month: 'Mei', cost: 5850 },
    { month: 'Jun', cost: 6200 }
  ]

  const wasteCategories = [
    { name: 'Idle Resources', value: 1840, color: '#ef4444' },
    { name: 'Over-provisioned', value: 680, color: '#f97316' },
    { name: 'Unutilized Storage', value: 280, color: '#eab308' },
    { name: 'Development/Test', value: 120, color: '#84cc16' }
  ]

  if (isLoading) {
    return (
      <>
        <div className="min-h-screen flex items-center justify-center bg-gray-50">
          <Card className="p-8 max-w-md w-full text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-green-600 mx-auto mb-4"></div>
            <h3 className="mb-2">AI analyseert je cloudkosten...</h3>
            <p className="text-gray-600 text-sm">
              Onze AI doorzoekt je infrastructuur op optimalisatiekansen
            </p>
            <Progress value={85} className="mt-4" />
            <p className="text-xs text-gray-500 mt-2">Bijna klaar...</p>
          </Card>
        </div>
      </>
    )
  }

  return (
    <>
      {/* Header */}
      <div className="bg-gradient-to-r from-green-600 to-green-700 text-white mx-4 rounded-2xl mb-8">
        <div className="max-w-6xl mx-auto px-4 sm:px-8 py-8">

          
          <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Badge className="bg-white/20 text-white">Cloudkostenscan</Badge>
                <Badge className="bg-white/20 text-white">Voltooid</Badge>
              </div>
              <h1 className="text-2xl lg:text-3xl text-white mb-2">
                Je AI-analyse is klaar
              </h1>
              <p className="text-green-100">
                Gegenereerd op {customerInfo?.analysisDate || new Date().toLocaleDateString('nl-NL', { 
                  day: 'numeric', 
                  month: 'long', 
                  year: 'numeric' 
                })}
              </p>
            </div>
            <div className="flex justify-end">
              <Button 
                onClick={handleDownloadPDF}
                className="bg-white text-green-600 hover:bg-green-50 text-[14px]"
              >
                Download PDF
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Customer Info Banner */}
      {customerInfo && (
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 mb-8">
          <div className="bg-white rounded-xl p-4 border border-gray-200 shadow-sm">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-green-100 rounded-full flex items-center justify-center">
                  <span className="text-green-600 text-lg">{customerInfo.name?.charAt(0) || 'A'}</span>
                </div>
                <div>
                  <div className="text-gray-900 font-medium">{customerInfo.name}</div>
                  <div className="text-gray-600 text-sm">{customerInfo.company}</div>
                </div>
              </div>
              <div className="text-right">
                <div className="text-gray-600 text-sm">Persoonlijke analyse voor</div>
                <div className="text-gray-900 text-sm font-medium">{customerInfo.email}</div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Key Metrics */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 mb-8">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <Card className="p-6 bg-gradient-to-br from-green-50 to-green-100">
            <div className="text-center">
              <div className="text-3xl text-green-600 mb-2">
                €{mockAnalysisData.projectedSavings.toLocaleString()}
              </div>
              <div className="text-gray-700 mb-1">Maandelijkse besparing</div>
              <div className="text-green-600 text-sm">
                {Math.round((mockAnalysisData.projectedSavings / mockAnalysisData.totalMonthlyCost) * 100)}% reductie
              </div>
            </div>
          </Card>
          
          <Card className="p-6">
            <div className="text-center">
              <div className="text-3xl text-[var(--color-apple-blue)] mb-2">{mockAnalysisData.optimizationScore}</div>
              <div className="text-gray-700 mb-1">Optimalisatie score</div>
              <div className="text-[var(--color-apple-blue)] text-sm">Goed voor verbetering</div>
            </div>
          </Card>
          
          <Card className="p-6">
            <div className="text-center">
              <div className="text-3xl text-purple-600 mb-2">{mockAnalysisData.recommendations}</div>
              <div className="text-gray-700 mb-1">Aanbevelingen</div>
              <div className="text-purple-600 text-sm">Direct implementeerbaar</div>
            </div>
          </Card>
          
          <Card className="p-6">
            <div className="text-center">
              <div className="text-3xl text-orange-600 mb-2">{mockAnalysisData.timeToImplement}</div>
              <div className="text-gray-700 mb-1">Implementatietijd</div>
              <div className="text-orange-600 text-sm">Geschatte doorlooptijd</div>
            </div>
          </Card>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 mb-8">
        <Tabs defaultValue="overview" className="w-full">
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="overview">Overzicht</TabsTrigger>
            <TabsTrigger value="breakdown">Kostenanalyse</TabsTrigger>
            <TabsTrigger value="recommendations">Aanbevelingen</TabsTrigger>
            <TabsTrigger value="implementation">Implementatie</TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Cost Trend */}
              <Card className="p-6">
                <h3 className="mb-4">Kostentrend (6 maanden)</h3>
                <ResponsiveContainer width="100%" height={250}>
                  <LineChart data={monthlyTrend}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="month" />
                    <YAxis />
                    <Tooltip formatter={(value) => [`€${value}`, 'Maandkosten']} />
                    <Line type="monotone" dataKey="cost" stroke="#16a34a" strokeWidth={3} />
                  </LineChart>
                </ResponsiveContainer>
              </Card>

              {/* Waste Distribution */}
              <Card className="p-6">
                <h3 className="mb-4">Verspilling per categorie</h3>
                <ResponsiveContainer width="100%" height={250}>
                  <PieChart>
                    <Pie
                      data={wasteCategories}
                      cx="50%"
                      cy="50%"
                      outerRadius={80}
                      dataKey="value"
                      label={({ name, value }) => `${name}: €${value}`}
                    >
                      {wasteCategories.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip formatter={(value) => [`€${value}`, 'Verspilling']} />
                  </PieChart>
                </ResponsiveContainer>
              </Card>
            </div>

            {/* Utilization Overview */}
            <Card className="p-6">
              <h3 className="mb-4">Resource gebruik overzicht</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                {utilizationData.map((item) => (
                  <div key={item.name} className="text-center">
                    <div className="text-lg mb-2">{item.name}</div>
                    <div className="relative w-20 h-20 mx-auto mb-2">
                      <svg className="w-20 h-20" viewBox="0 0 36 36">
                        <path
                          className="text-gray-300"
                          stroke="currentColor"
                          strokeWidth="3"
                          fill="transparent"
                          d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                        />
                        <path
                          className="text-green-600"
                          stroke="currentColor"
                          strokeWidth="3"
                          strokeDasharray={`${item.utilized}, 100`}
                          fill="transparent"
                          d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                        />
                      </svg>
                      <div className="absolute inset-0 flex items-center justify-center">
                        <span className="text-sm">{item.utilized}%</span>
                      </div>
                    </div>
                    <div className="text-xs text-gray-600">Gebruikt</div>
                  </div>
                ))}
              </div>
            </Card>
          </TabsContent>

          <TabsContent value="breakdown" className="space-y-6">
            <Card className="p-6">
              <h3 className="mb-4">Gedetailleerde kostenanalyse</h3>
              <ResponsiveContainer width="100%" height={400}>
                <BarChart data={costBreakdown}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="name" angle={-45} textAnchor="end" height={100} />
                  <YAxis />
                  <Tooltip formatter={(value) => [`€${value}`, '']} />
                  <Bar dataKey="current" fill="#ef4444" name="Huidige kosten" />
                  <Bar dataKey="optimized" fill="#16a34a" name="Na optimalisatie" />
                </BarChart>
              </ResponsiveContainer>
            </Card>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {costBreakdown.map((item) => (
                <Card key={item.name} className="p-6">
                  <div className="flex justify-between items-start mb-3">
                    <h4>{item.name}</h4>
                    <Badge variant="outline" className="text-green-600">
                      -€{item.savings}/maand
                    </Badge>
                  </div>
                  <div className="space-y-2">
                    <div className="flex justify-between">
                      <span className="text-sm text-gray-600">Huidig</span>
                      <span className="text-sm">€{item.current}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-sm text-gray-600">Geoptimaliseerd</span>
                      <span className="text-sm text-green-600">€{item.optimized}</span>
                    </div>
                    <div className="flex justify-between font-medium">
                      <span className="text-sm">Besparing</span>
                      <span className="text-sm text-green-600">€{item.savings}</span>
                    </div>
                  </div>
                </Card>
              ))}
            </div>
          </TabsContent>

          <TabsContent value="recommendations" className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <Card className="p-6">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 bg-red-100 rounded-full flex items-center justify-center">
                    <span className="w-2 h-2 bg-red-600 rounded-full"></span>
                  </div>
                  <div>
                    <h4>Hoge prioriteit</h4>
                    <p className="text-sm text-gray-600">Direct implementeren</p>
                  </div>
                </div>
                <ul className="space-y-3">
                  <li className="flex items-start gap-3">
                    <span className="text-red-500 mt-1">•</span>
                    <div>
                      <div className="font-medium">Stop idle EC2 instances</div>
                      <div className="text-sm text-gray-600">15 instances draaien onnodig 24/7</div>
                      <div className="text-sm text-green-600">Besparing: €1.240/maand</div>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-red-500 mt-1">•</span>
                    <div>
                      <div className="font-medium">Verwijder ongebruikte EBS volumes</div>
                      <div className="text-sm text-gray-600">3.2TB aan ongebruikte opslag</div>
                      <div className="text-sm text-green-600">Besparing: €280/maand</div>
                    </div>
                  </li>
                </ul>
              </Card>

              <Card className="p-6">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 bg-orange-100 rounded-full flex items-center justify-center">
                    <span className="w-2 h-2 bg-orange-600 rounded-full"></span>
                  </div>
                  <div>
                    <h4>Gemiddelde prioriteit</h4>
                    <p className="text-sm text-gray-600">Deze maand implementeren</p>
                  </div>
                </div>
                <ul className="space-y-3">
                  <li className="flex items-start gap-3">
                    <span className="text-orange-500 mt-1">•</span>
                    <div>
                      <div className="font-medium">Right-size over-provisioned instances</div>
                      <div className="text-sm text-gray-600">8 instances kunnen kleiner</div>
                      <div className="text-sm text-green-600">Besparing: €890/maand</div>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-orange-500 mt-1">•</span>
                    <div>
                      <div className="font-medium">Implementeer auto-scaling</div>
                      <div className="text-sm text-gray-600">Voor development omgevingen</div>
                      <div className="text-sm text-green-600">Besparing: €320/maand</div>
                    </div>
                  </li>
                </ul>
              </Card>

              <Card className="p-6">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 bg-[var(--color-apple-gray-6)] rounded-full flex items-center justify-center">
                    <span className="w-2 h-2 bg-[var(--color-apple-blue)] rounded-full"></span>
                  </div>
                  <div>
                    <h4>Strategische optimalisaties</h4>
                    <p className="text-sm text-gray-600">Langetermijn besparingen</p>
                  </div>
                </div>
                <ul className="space-y-3">
                  <li className="flex items-start gap-3">
                    <span className="text-[var(--color-apple-gray-6)]0 mt-1">•</span>
                    <div>
                      <div className="font-medium">Reserved Instances voor stable workloads</div>
                      <div className="text-sm text-gray-600">3-jaar commitment aanbevolen</div>
                      <div className="text-sm text-green-600">Besparing: €680/maand</div>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-[var(--color-apple-gray-6)]0 mt-1">•</span>
                    <div>
                      <div className="font-medium">Migreer naar Graviton instances</div>
                      <div className="text-sm text-gray-600">Betere price/performance ratio</div>
                      <div className="text-sm text-green-600">Besparing: €420/maand</div>
                    </div>
                  </li>
                </ul>
              </Card>

              <Card className="p-6">
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 bg-green-100 rounded-full flex items-center justify-center">
                    <span className="w-2 h-2 bg-green-600 rounded-full"></span>
                  </div>
                  <div>
                    <h4>Governance & Monitoring</h4>
                    <p className="text-sm text-gray-600">Preventieve maatregelen</p>
                  </div>
                </div>
                <ul className="space-y-3">
                  <li className="flex items-start gap-3">
                    <span className="text-green-500 mt-1">•</span>
                    <div>
                      <div className="font-medium">Setup cost budgets & alerts</div>
                      <div className="text-sm text-gray-600">Voorkom onverwachte kosten</div>
                    </div>
                  </li>
                  <li className="flex items-start gap-3">
                    <span className="text-green-500 mt-1">•</span>
                    <div>
                      <div className="font-medium">Tag resources voor cost allocation</div>
                      <div className="text-sm text-gray-600">Beter inzicht per project/team</div>
                    </div>
                  </li>
                </ul>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="implementation" className="space-y-6">
            <Card className="p-6">
              <h3 className="mb-4">3-fasen implementatieplan</h3>
              <div className="space-y-6">
                <div>
                  <div className="flex items-center gap-3 mb-3">
                    <div className="w-8 h-8 bg-red-100 rounded-full flex items-center justify-center">
                      <span className="text-red-600 text-sm">1</span>
                    </div>
                    <div>
                      <h4>Week 1: Quick Wins</h4>
                      <p className="text-sm text-gray-600">Directe besparingen zonder risico</p>
                    </div>
                    <Badge className="bg-red-100 text-red-600">€1.520/maand</Badge>
                  </div>
                  <div className="ml-11 space-y-2">
                    <div className="text-sm">✓ Stop alle idle instances</div>
                    <div className="text-sm">✓ Verwijder ongebruikte EBS volumes</div>
                    <div className="text-sm">✓ Cleanup oude snapshots</div>
                    <div className="text-sm">✓ Schedule dev/test omgevingen</div>
                  </div>
                </div>

                <Separator />

                <div>
                  <div className="flex items-center gap-3 mb-3">
                    <div className="w-8 h-8 bg-orange-100 rounded-full flex items-center justify-center">
                      <span className="text-orange-600 text-sm">2</span>
                    </div>
                    <div>
                      <h4>Week 2-3: Right-sizing</h4>
                      <p className="text-sm text-gray-600">Optimaliseer resource allocaties</p>
                    </div>
                    <Badge className="bg-orange-100 text-orange-600">€890/maand</Badge>
                  </div>
                  <div className="ml-11 space-y-2">
                    <div className="text-sm">⚡ Downsize over-provisioned instances</div>
                    <div className="text-sm">⚡ Implementeer auto-scaling groups</div>
                    <div className="text-sm">⚡ Optimize database instance types</div>
                    <div className="text-sm">⚡ Review en aanpassen storage types</div>
                  </div>
                </div>

                <Separator />

                <div>
                  <div className="flex items-center gap-3 mb-3">
                    <div className="w-8 h-8 bg-[var(--color-apple-gray-6)] rounded-full flex items-center justify-center">
                      <span className="text-[var(--color-apple-blue)] text-sm">3</span>
                    </div>
                    <div>
                      <h4>Week 4-6: Strategische optimalisaties</h4>
                      <p className="text-sm text-gray-600">Langetermijn besparingen</p>
                    </div>
                    <Badge className="bg-[var(--color-apple-gray-6)] text-[var(--color-apple-blue)]">€1.100/maand</Badge>
                  </div>
                  <div className="ml-11 space-y-2">
                    <div className="text-sm">• Purchase Reserved Instances</div>
                    <div className="text-sm">• Migratie naar Graviton processors</div>
                    <div className="text-sm">• Setup comprehensive monitoring</div>
                    <div className="text-sm">• Implementeer cost governance</div>
                  </div>
                </div>
              </div>
            </Card>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <Card className="p-6">
                <h4 className="mb-4">ROI Timeline</h4>
                <div className="space-y-3">
                  <div className="flex justify-between">
                    <span>Week 1</span>
                    <span className="text-green-600">€1.520 besparing</span>
                  </div>
                  <div className="flex justify-between">
                    <span>Week 3</span>
                    <span className="text-green-600">€2.410 besparing</span>
                  </div>
                  <div className="flex justify-between">
                    <span>Week 6</span>
                    <span className="text-green-600">€3.510 besparing</span>
                  </div>
                  <Separator />
                  <div className="flex justify-between font-medium">
                    <span>Totaal jaar 1</span>
                    <span className="text-green-600">€42.120 besparing</span>
                  </div>
                </div>
              </Card>

              <Card className="p-6">
                <h4 className="mb-4">Risk Assessment</h4>
                <div className="space-y-3">
                  <div className="flex items-center gap-2">
                    <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                    <span className="text-sm">Laag risico: €1.520/maand</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-3 h-3 bg-yellow-500 rounded-full"></div>
                    <span className="text-sm">Gemiddeld risico: €890/maand</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-3 h-3 bg-[var(--color-apple-blue)] rounded-full"></div>
                    <span className="text-sm">Planning vereist: €1.100/maand</span>
                  </div>
                  <div className="text-xs text-gray-600 mt-3">
                    Alle aanbevelingen zijn gebaseerd op industry best practices 
                    en AWS Well-Architected Framework principes.
                  </div>
                </div>
              </Card>
            </div>
          </TabsContent>
        </Tabs>
      </div>

      {/* Bottom CTA */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 mb-8">
        <Card className="p-8 bg-gradient-to-r from-green-50 to-green-100 text-center">
          <h3 className="mb-4">Klaar om €2.850 per maand te besparen?</h3>
          <p className="text-gray-600 mb-6">
            Dit rapport bevat alles wat je nodig hebt om direct te starten met kostenoptimalisatie.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              onClick={handleDownloadPDF}
              className="bg-green-600 hover:bg-green-700 text-white text-[14px]"
            >
              Download volledige analyse
            </Button>
            <a href="#/contact">
              <Button 
                variant="outline" 
                className="border-green-600 text-green-600 hover:bg-green-50 text-[14px]"
              >
                Hulp bij implementatie?
              </Button>
            </a>
          </div>
        </Card>
      </div>
    </>
  )
}