'use client'

import React, { useState, useEffect } from 'react'
import { Button } from '../ui/button'
import { Card } from '../ui/card'
import { Badge } from '../ui/badge'
import { Progress } from '../ui/progress'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs'
import { Separator } from '../ui/separator'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, ScatterChart, Scatter } from 'recharts'

export function PrijsstrategieResultatenPage() {
  const [scanData, setScanData] = useState<any>(null)
  const [customerInfo, setCustomerInfo] = useState<any>(null)
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    // Simulate loading and get data from localStorage
    const timer = setTimeout(() => {
      const storedData = localStorage.getItem('simium_scan_data')
      if (storedData) {
        const parsed = JSON.parse(storedData)
        if (parsed.scanType === 'prijsstrategie') {
          setScanData(parsed.data)
        }
      }
      
      // Get customer info from localStorage or use mock data
      const customerData = localStorage.getItem('simium_customer_info')
      if (customerData) {
        setCustomerInfo(JSON.parse(customerData))
      } else {
        // Mock customer data for demo
        setCustomerInfo({
          name: 'David Bakker',
          company: 'Premium Services Nederland',
          email: 'david@premiumservices.nl',
          analysisDate: new Date().toLocaleDateString('nl-NL', { 
            day: 'numeric', 
            month: 'long', 
            year: 'numeric' 
          })
        })
      }
      
      setIsLoading(false)
    }, 1500)

    return () => clearTimeout(timer)
  }, [])

  const handleDownloadPDF = () => {
    const element = document.createElement('a')
    const file = new Blob(['Prijsstrategie Analyse Rapport - Generated by Simium AI'], { type: 'text/plain' })
    element.href = URL.createObjectURL(file)
    element.download = 'simium-prijsstrategie-analyse.pdf'
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  // Mock data based on scan inputs
  const mockAnalysisData = {
    optimizationPotential: scanData?.calculatedPotential || 28,
    currentMargin: 35,
    optimizedMargin: 45,
    revenueIncrease: 8400,
    competitivePosition: 'Onderprijs'
  }

  const pricingBenchmark = [
    { segment: 'Budget', yourPrice: 45, marketAvg: 52, premium: 65, volume: 30 },
    { segment: 'Standard', yourPrice: 85, marketAvg: 95, premium: 120, volume: 50 },
    { segment: 'Premium', yourPrice: 150, marketAvg: 180, premium: 250, volume: 20 }
  ]

  const competitorAnalysis = [
    { name: 'Concurrent A', price: 95, quality: 8, marketShare: 25 },
    { name: 'Concurrent B', price: 120, quality: 9, marketShare: 20 },
    { name: 'Concurrent C', price: 75, quality: 6, marketShare: 15 },
    { name: 'Jouw bedrijf', price: 85, quality: 8, marketShare: 12 },
    { name: 'Concurrent D', price: 110, quality: 7, marketShare: 10 }
  ]

  const marginAnalysis = [
    { product: 'Basisservice', currentMargin: 25, optimizedMargin: 35, volume: 40 },
    { product: 'Standaard package', currentMargin: 35, optimizedMargin: 48, volume: 35 },
    { product: 'Premium service', currentMargin: 45, optimizedMargin: 60, volume: 15 },
    { product: 'Enterprise', currentMargin: 55, optimizedMargin: 65, volume: 10 }
  ]

  const segmentationOpportunities = [
    { segment: 'Startups', currentPrice: 75, suggestedPrice: 65, reasoning: 'Prijsgevoelig segment, meer volume mogelijk' },
    { segment: 'MKB', currentPrice: 85, suggestedPrice: 110, reasoning: 'Onderprijs, bereid meer te betalen voor kwaliteit' },
    { segment: 'Enterprise', currentPrice: 150, suggestedPrice: 195, reasoning: 'Zoekt premium service, prijs minder belangrijk' },
    { segment: 'Non-profit', currentPrice: 85, suggestedPrice: 70, reasoning: 'Maatschappelijke korting rechtvaardigt lagere marge' }
  ]

  const priceElasticity = [
    { change: -20, demand: 140, revenue: 95 },
    { change: -10, demand: 115, revenue: 98 },
    { change: 0, demand: 100, revenue: 100 },
    { change: 10, demand: 90, revenue: 102 },
    { change: 20, demand: 75, revenue: 98 },
    { change: 30, demand: 65, revenue: 92 }
  ]

  if (isLoading) {
    return (
      <>
        <div className="min-h-screen flex items-center justify-center bg-gray-50">
          <Card className="p-8 max-w-md w-full text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-600 mx-auto mb-4"></div>
            <h3 className="mb-2">AI analyseert je prijsstrategie...</h3>
            <p className="text-gray-600 text-sm">
              Onze AI vergelijkt je prijzen met marktdata en identificeert optimalisaties
            </p>
            <Progress value={90} className="mt-4" />
            <p className="text-xs text-gray-500 mt-2">Benchmarking...</p>
          </Card>
        </div>
      </>
    )
  }

  return (
    <>
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-600 to-purple-700 text-white mx-4 rounded-2xl mb-8">
        <div className="max-w-6xl mx-auto px-4 sm:px-8 py-8">

          
          <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-4">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Badge className="bg-white/20 text-white">Prijsstrategie-check</Badge>
                <Badge className="bg-white/20 text-white">Voltooid</Badge>
              </div>
              <h1 className="text-2xl lg:text-3xl text-white mb-2">
                Je prijsstrategie-analyse is klaar
              </h1>
              <p className="text-purple-100">
                Gegenereerd op {customerInfo?.analysisDate || new Date().toLocaleDateString('nl-NL', { 
                  day: 'numeric', 
                  month: 'long', 
                  year: 'numeric' 
                })}
              </p>
            </div>
            <div className="flex justify-end">
              <Button 
                onClick={handleDownloadPDF}
                className="bg-white text-purple-600 hover:bg-purple-50 text-[14px]"
              >
                Download PDF
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Customer Info Banner */}
      {customerInfo && (
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 mb-8">
          <div className="bg-white rounded-xl p-4 border border-gray-200 shadow-sm">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-purple-100 rounded-full flex items-center justify-center">
                  <span className="text-purple-600 text-lg">{customerInfo.name?.charAt(0) || 'D'}</span>
                </div>
                <div>
                  <div className="text-gray-900 font-medium">{customerInfo.name}</div>
                  <div className="text-gray-600 text-sm">{customerInfo.company}</div>
                </div>
              </div>
              <div className="text-right">
                <div className="text-gray-600 text-sm">Persoonlijke analyse voor</div>
                <div className="text-gray-900 text-sm font-medium">{customerInfo.email}</div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Key Metrics */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 mb-8">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <Card className="p-6 bg-gradient-to-br from-purple-50 to-purple-100">
            <div className="text-center">
              <div className="text-3xl text-purple-600 mb-2">{mockAnalysisData.optimizationPotential}%</div>
              <div className="text-gray-700 mb-1">Optimalisatiepotentieel</div>
              <div className="text-purple-600 text-sm">Zeer hoog potentieel</div>
            </div>
          </Card>
          
          <Card className="p-6">
            <div className="text-center">
              <div className="text-3xl text-green-600 mb-2">
                €{mockAnalysisData.revenueIncrease.toLocaleString()}
              </div>
              <div className="text-gray-700 mb-1">Extra omzet/maand</div>
              <div className="text-green-600 text-sm">Bij implementatie</div>
            </div>
          </Card>
          
          <Card className="p-6">
            <div className="text-center">
              <div className="text-3xl text-[var(--color-apple-blue)] mb-2">
                {mockAnalysisData.currentMargin}% → {mockAnalysisData.optimizedMargin}%
              </div>
              <div className="text-gray-700 mb-1">Marge verbetering</div>
              <div className="text-[var(--color-apple-blue)] text-sm">+10 procentpunten</div>
            </div>
          </Card>
          
          <Card className="p-6">
            <div className="text-center">
              <div className="text-3xl text-orange-600 mb-2">{mockAnalysisData.competitivePosition}</div>
              <div className="text-gray-700 mb-1">Marktpositie</div>
              <div className="text-orange-600 text-sm">Ruimte voor verhoging</div>
            </div>
          </Card>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 mb-8">
        <Tabs defaultValue="benchmark" className="w-full">
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="benchmark">Benchmark</TabsTrigger>
            <TabsTrigger value="competition">Concurrentie</TabsTrigger>
            <TabsTrigger value="segmentation">Segmentatie</TabsTrigger>
            <TabsTrigger value="strategy">Strategie</TabsTrigger>
          </TabsList>

          <TabsContent value="benchmark" className="space-y-6">
            <Card className="p-6">
              <h3 className="mb-4">Prijsbenchmark per segment</h3>
              <ResponsiveContainer width="100%" height={400}>
                <BarChart data={pricingBenchmark}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="segment" />
                  <YAxis />
                  <Tooltip formatter={(value) => [`€${value}`, '']} />
                  <Bar dataKey="yourPrice" fill="#7c3aed" name="Jouw prijs" />
                  <Bar dataKey="marketAvg" fill="#3b82f6" name="Marktgemiddelde" />
                  <Bar dataKey="premium" fill="#10b981" name="Premium spelers" />
                </BarChart>
              </ResponsiveContainer>
            </Card>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <Card className="p-6">
                <h4 className="mb-4">Margeanalyse per product</h4>
                <div className="space-y-4">
                  {marginAnalysis.map((product) => (
                    <div key={product.product} className="border-b border-gray-200 pb-3 last:border-b-0">
                      <div className="flex justify-between items-start mb-2">
                        <div>
                          <div className="font-medium">{product.product}</div>
                          <div className="text-sm text-gray-600">{product.volume}% van volume</div>
                        </div>
                        <Badge variant="outline" className="text-green-600">
                          +{product.optimizedMargin - product.currentMargin}pp
                        </Badge>
                      </div>
                      <div className="space-y-1">
                        <div className="flex justify-between text-sm">
                          <span>Huidige marge</span>
                          <span>{product.currentMargin}%</span>
                        </div>
                        <div className="flex justify-between text-sm">
                          <span>Geoptimaliseerd</span>
                          <span className="text-green-600">{product.optimizedMargin}%</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </Card>

              <Card className="p-6">
                <h4 className="mb-4">Prijselasticiteit analyse</h4>
                <ResponsiveContainer width="100%" height={250}>
                  <ScatterChart data={priceElasticity}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="change" domain={[-25, 35]} name="Prijsverandering %" />
                    <YAxis dataKey="revenue" domain={[90, 105]} name="Omzet impact %" />
                    <Tooltip formatter={(value, name) => [`${value}%`, name === 'revenue' ? 'Omzet impact' : 'Prijsverandering']} />
                    <Scatter dataKey="revenue" fill="#7c3aed" />
                  </ScatterChart>
                </ResponsiveContainer>
                <div className="text-center mt-2">
                  <div className="text-sm text-gray-600">Sweet spot: +10% prijs = +2% omzet</div>
                </div>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="competition" className="space-y-6">
            <Card className="p-6">
              <h3 className="mb-4">Concurrentiepositionering</h3>
              <ResponsiveContainer width="100%" height={400}>
                <ScatterChart data={competitorAnalysis}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="price" name="Prijs" domain={[60, 130]} />
                  <YAxis dataKey="quality" name="Kwaliteit score" domain={[5, 10]} />
                  <Tooltip formatter={(value, name) => [
                    name === 'price' ? `€${value}` : value,
                    name === 'price' ? 'Prijs' : name === 'quality' ? 'Kwaliteit' : 'Marktaandeel'
                  ]} />
                  <Scatter dataKey="marketShare" fill="#7c3aed" />
                </ScatterChart>
              </ResponsiveContainer>
              <div className="mt-4 text-center text-sm text-gray-600">
                Bubble grootte = marktaandeel | Jouw positie: onderprijs voor kwaliteitsniveau
              </div>
            </Card>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <Card className="p-6">
                <h4 className="mb-4">🎯 Concurrentie benchmark</h4>
                <div className="space-y-4">
                  {competitorAnalysis.map((competitor) => (
                    <div key={competitor.name} className="flex justify-between items-center">
                      <div>
                        <div className={`font-medium ${competitor.name === 'Jouw bedrijf' ? 'text-purple-600' : ''}`}>
                          {competitor.name}
                        </div>
                        <div className="text-sm text-gray-600">
                          Kwaliteit: {competitor.quality}/10 | Marktaandeel: {competitor.marketShare}%
                        </div>
                      </div>
                      <div className="text-right">
                        <div className={`text-lg ${competitor.name === 'Jouw bedrijf' ? 'text-purple-600' : ''}`}>
                          €{competitor.price}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </Card>

              <Card className="p-6">
                <h4 className="mb-4">🏆 Concurrentievoordelen</h4>
                <div className="space-y-4">
                  <div className="flex items-start gap-3">
                    <span className="text-green-500 mt-1">✓</span>
                    <div>
                      <div className="font-medium">Kwaliteit-prijs verhouding</div>
                      <div className="text-sm text-gray-600">Jouw kwaliteit (8/10) vs gemiddelde prijs concurrent</div>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <span className="text-green-500 mt-1">✓</span>
                    <div>
                      <div className="font-medium">Marktpositie voor verbetering</div>
                      <div className="text-sm text-gray-600">25% ruimte voor prijsverhoging naar marktgemiddelde</div>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <span className="text-orange-500 mt-1">⚠</span>
                    <div>
                      <div className="font-medium">Marktaandeel relatief laag</div>
                      <div className="text-sm text-gray-600">12% vs 20-25% van top concurrenten</div>
                    </div>
                  </div>
                </div>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="segmentation" className="space-y-6">
            <Card className="p-6">
              <h3 className="mb-4">Klantsegmentatie optimalisatie</h3>
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {segmentationOpportunities.map((segment) => (
                  <Card key={segment.segment} className="p-4 border">
                    <div className="flex justify-between items-start mb-3">
                      <h4>{segment.segment}</h4>
                      <Badge 
                        variant="outline"
                        className={
                          segment.suggestedPrice > segment.currentPrice 
                            ? 'text-green-600 border-green-600' 
                            : 'text-[var(--color-apple-blue)] border-[var(--color-apple-blue)]'
                        }
                      >
                        {segment.suggestedPrice > segment.currentPrice ? '+' : ''}
                        {Math.round(((segment.suggestedPrice - segment.currentPrice) / segment.currentPrice) * 100)}%
                      </Badge>
                    </div>
                    <div className="space-y-2 mb-3">
                      <div className="flex justify-between">
                        <span className="text-sm text-gray-600">Huidige prijs</span>
                        <span className="text-sm">€{segment.currentPrice}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-sm text-gray-600">Aanbevolen prijs</span>
                        <span className={`text-sm ${segment.suggestedPrice > segment.currentPrice ? 'text-green-600' : 'text-[var(--color-apple-blue)]'}`}>
                          €{segment.suggestedPrice}
                        </span>
                      </div>
                    </div>
                    <p className="text-sm text-gray-600">{segment.reasoning}</p>
                  </Card>
                ))}
              </div>
            </Card>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <Card className="p-6">
                <h4 className="mb-4">Value-based pricing opportunities</h4>
                <div className="space-y-4">
                  <div className="border-l-4 border-green-500 pl-4">
                    <div className="font-medium">ROI-based pricing</div>
                    <div className="text-sm text-gray-600">
                      Voor Enterprise: prijs gebaseerd op besparingen die je levert
                    </div>
                    <div className="text-sm text-green-600">Potentieel: +40% marge</div>
                  </div>
                  
                  <div className="border-l-4 border-[var(--color-apple-blue)] pl-4">
                    <div className="font-medium">Tijdsbesparing premium</div>
                    <div className="text-sm text-gray-600">
                      Snelle implementatie als premium service
                    </div>
                    <div className="text-sm text-[var(--color-apple-blue)]">Potentieel: +25% prijs</div>
                  </div>
                  
                  <div className="border-l-4 border-purple-500 pl-4">
                    <div className="font-medium">Outcome garanties</div>
                    <div className="text-sm text-gray-600">
                      Resultaat-gegarandeerde pakketten
                    </div>
                    <div className="text-sm text-purple-600">Potentieel: +60% marge</div>
                  </div>
                </div>
              </Card>

              <Card className="p-6">
                <h4 className="mb-4">Bundeling strategieën</h4>
                <div className="space-y-4">
                  <div>
                    <div className="font-medium mb-2">📦 Pakket optimalisatie</div>
                    <div className="text-sm text-gray-600 mb-2">
                      Combineer populaire services in aantrekkelijke bundels
                    </div>
                    <div className="text-xs bg-gray-100 p-2 rounded">
                      Basis (€85) + Premium add-ons (€45) = €110 bundel (-€20 korting)
                    </div>
                  </div>
                  
                  <div>
                    <div className="font-medium mb-2">⚡ Frequentie korting</div>
                    <div className="text-sm text-gray-600 mb-2">
                      Jaarcontracten vs maandelijks met korting
                    </div>
                    <div className="text-xs bg-gray-100 p-2 rounded">
                      Jaarcontract: 10% korting maar betere cashflow
                    </div>
                  </div>
                  
                  <div>
                    <div className="font-medium mb-2">🎯 Volume incentives</div>
                    <div className="text-sm text-gray-600 mb-2">
                      Schaalvoordelen bij meerdere projecten
                    </div>
                    <div className="text-xs bg-gray-100 p-2 rounded">
                      2e project: -5% | 3+ projecten: -10%
                    </div>
                  </div>
                </div>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="strategy" className="space-y-6">
            <Card className="p-6">
              <h3 className="mb-4">🚀 Implementatie strategie</h3>
              <div className="space-y-6">
                <div className="flex items-start gap-4">
                  <div className="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center flex-shrink-0">
                    <span className="text-green-600 text-sm">1</span>
                  </div>
                  <div className="flex-1">
                    <h5>Fase 1: Direct implementeerbaar (Week 1-2)</h5>
                    <p className="text-sm text-gray-600 mb-3">Start met laag-risico optimalisaties</p>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="bg-green-50 p-3 rounded">
                        <div className="font-medium text-green-800">MKB segment</div>
                        <div className="text-sm text-green-600">€85 → €110 (+29%)</div>
                        <div className="text-xs text-green-600">Risico: Laag | ROI: Hoog</div>
                      </div>
                      <div className="bg-green-50 p-3 rounded">
                        <div className="font-medium text-green-800">Enterprise upsell</div>
                        <div className="text-sm text-green-600">Premium services +€45</div>
                        <div className="text-xs text-green-600">Bestaande klanten first</div>
                      </div>
                    </div>
                    <div className="mt-2 text-sm text-green-600">Impact: +€3.200/maand</div>
                  </div>
                </div>

                <div className="flex items-start gap-4">
                  <div className="w-8 h-8 bg-[var(--color-apple-gray-6)] rounded-full flex items-center justify-center flex-shrink-0">
                    <span className="text-[var(--color-apple-blue)] text-sm">2</span>
                  </div>
                  <div className="flex-1">
                    <h5>Fase 2: Segmentatie optimalisatie (Week 3-6)</h5>
                    <p className="text-sm text-gray-600 mb-3">Implementeer gedifferentieerde pricing</p>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="bg-[var(--color-apple-gray-6)] p-3 rounded">
                        <div className="font-medium text-[var(--color-apple-gray)]">Startup pricing</div>
                        <div className="text-sm text-[var(--color-apple-blue)]">€75 → €65 (volume play)</div>
                        <div className="text-xs text-[var(--color-apple-blue)]">Target: +40% volume</div>
                      </div>
                      <div className="bg-[var(--color-apple-gray-6)] p-3 rounded">
                        <div className="font-medium text-[var(--color-apple-gray)]">Enterprise premium</div>
                        <div className="text-sm text-[var(--color-apple-blue)]">€150 → €195 (+30%)</div>
                        <div className="text-xs text-[var(--color-apple-blue)]">Value-based positioning</div>
                      </div>
                    </div>
                    <div className="mt-2 text-sm text-[var(--color-apple-blue)]">Impact: +€2.800/maand</div>
                  </div>
                </div>

                <div className="flex items-start gap-4">
                  <div className="w-8 h-8 bg-purple-100 rounded-full flex items-center justify-center flex-shrink-0">
                    <span className="text-purple-600 text-sm">3</span>
                  </div>
                  <div className="flex-1">
                    <h5>Fase 3: Strategische optimalisatie (Maand 2-3)</h5>
                    <p className="text-sm text-gray-600 mb-3">Lange-termijn value creation</p>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="bg-purple-50 p-3 rounded">
                        <div className="font-medium text-purple-800">ROI-based pricing</div>
                        <div className="text-sm text-purple-600">Performance guarantees</div>
                        <div className="text-xs text-purple-600">Premium pricing model</div>
                      </div>
                      <div className="bg-purple-50 p-3 rounded">
                        <div className="font-medium text-purple-800">Bundling strategy</div>
                        <div className="text-sm text-purple-600">Package optimization</div>
                        <div className="text-xs text-purple-600">Higher customer value</div>
                      </div>
                    </div>
                    <div className="mt-2 text-sm text-purple-600">Impact: +€2.400/maand</div>
                  </div>
                </div>
              </div>
            </Card>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <Card className="p-6">
                <h4 className="mb-4">Risk mitigation</h4>
                <div className="space-y-3">
                  <div className="flex items-start gap-3">
                    <span className="text-green-500 mt-1">✓</span>
                    <div>
                      <div className="font-medium">A/B test prijswijzigingen</div>
                      <div className="text-sm text-gray-600">Test nieuwe prijzen met 20% van nieuwe klanten eerst</div>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <span className="text-green-500 mt-1">✓</span>
                    <div>
                      <div className="font-medium">Bestaande klanten geleidelijk</div>
                      <div className="text-sm text-gray-600">3 maanden opzegtermijn voor contractvernieuwing</div>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <span className="text-green-500 mt-1">✓</span>
                    <div>
                      <div className="font-medium">Value communicatie eerst</div>
                      <div className="text-sm text-gray-600">Toon extra waarde voor prijsverhoging</div>
                    </div>
                  </div>
                </div>
              </Card>

              <Card className="p-6">
                <h4 className="mb-4">Success metrics</h4>
                <div className="space-y-3">
                  <div className="flex justify-between">
                    <span className="text-sm">Totale omzetverhoging</span>
                    <span className="font-medium text-green-600">+€8.400/maand</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm">Gemiddelde marge</span>
                    <span className="font-medium text-[var(--color-apple-blue)]">35% → 45%</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm">Klantbehoud target</span>
                    <span className="font-medium text-purple-600">&gt;92%</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-sm">ROI implementatie</span>
                    <span className="font-medium text-orange-600">2.100%</span>
                  </div>
                  <Separator />
                  <div className="flex justify-between font-medium">
                    <span>Jaar 1 extra winst</span>
                    <span className="text-green-600">€100.800</span>
                  </div>
                </div>
              </Card>
            </div>
          </TabsContent>
        </Tabs>
      </div>

      {/* Bottom CTA */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 mb-8">
        <Card className="p-8 bg-gradient-to-r from-purple-50 to-purple-100 text-center">
          <h3 className="mb-4">Klaar om 28% meer marge te behalen?</h3>
          <p className="text-gray-600 mb-6">
            Verhoog je omzet met €8.400 per maand door onze prijsstrategie te implementeren.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button 
              onClick={handleDownloadPDF}
              className="bg-purple-600 hover:bg-purple-700 text-white text-[14px]"
            >
              📄 Download volledige analyse
            </Button>
            <a href="#/contact">
              <Button 
                variant="outline" 
                className="border-purple-600 text-purple-600 hover:bg-purple-50 text-[14px]"
              >
                Hulp bij implementatie?
              </Button>
            </a>
          </div>
        </Card>
      </div>
    </>
  )
}